# Generated by Django 3.2.11 on 2022-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0003_auto_20210419_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxvm',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
