# Generated by Django 3.2.12 on 2022-02-18 21:48

from django.db import migrations, models
import django.db.models.deletion
import netbox_proxbox.mixin.ModelDiffMixin
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0026_vminterface_bridge'),
        ('dcim', '0144_fix_cable_abs_length'),
        ('netbox_proxbox', '0004_alter_proxmoxvm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(default='undefined', max_length=255)),
                ('status', models.CharField(default='unknown', max_length=255)),
                ('message', models.CharField(blank=True, max_length=512, null=True)),
                ('fail_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('done', models.BooleanField(default=False)),
                ('remove_unused', models.BooleanField(default=True)),
                ('scheduled_time', models.DateTimeField(blank=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.cluster')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netbox_proxbox.synctask')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.virtualmachine')),
            ],
            options={
                'abstract': False,
            },
            bases=(netbox_proxbox.mixin.ModelDiffMixin.ModelDiffMixin, models.Model),
        ),
    ]
