# Generated by Django 3.2.12 on 2022-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0006_auto_20220419_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='data_instance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
