# Generated by Django 3.2.12 on 2022-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0008_auto_20220503_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='finish_remove_unused',
            field=models.CharField(default='not_started', max_length=255),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
