# Generated by Django 3.2.12 on 2022-07-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0011_auto_20220725_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='proxmox_vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_proxbox.proxmoxvm'),
        ),
    ]
