# Generated by Django 3.2.12 on 2022-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0012_synctask_proxmox_vm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxvm',
            name='disk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='memory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='proxmox_vm_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='vcpus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
