# Generated by Django 3.2.12 on 2022-07-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0026_vminterface_bridge'),
        ('netbox_proxbox', '0013_auto_20220726_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxvm',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='node',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualization.virtualmachine'),
        ),
    ]
