# Generated by Django 3.2.12 on 2022-07-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0144_fix_cable_abs_length'),
        ('virtualization', '0026_vminterface_bridge'),
        ('netbox_proxbox', '0015_alter_synctask_proxmox_vm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxvm',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.cluster'),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.virtualmachine'),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_proxbox.synctask'),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='proxmox_vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_proxbox.proxmoxvm'),
        ),
    ]
